### ISSUE TITLE
Add table finance_financials

### ISSUE THREAD

**Issue by macleanpinto** [turbot/steampipe-plugin-finance#2]
Yahoo finance provides financials about a company.  This information is not included in the plugin

https://finance.yahoo.com/quote/MSFT/financials?p=MSFT

**Comment by e-gineer** [comment]
Hey @macleanpinto ... would be great to have this data in a table ... do you know if there are APIs available for this data?

**Comment by macleanpinto** [comment]
Hi Nathan, I have found a Reddit link with most updated API links

reddit.com/r/sheets/wiki/apis/finance. I am working on add earnings table

**Comment by e-gineer** [comment]
Nice find @macleanpinto ! The modules for Yahoo Finance look like a great source :-)

**Comment by macleanpinto** [comment]
@e-gineer  I have made the changes required for earnings module. Here is the PR for reference https://github.com/turbot/steampipe-plugin-finance/pull/3
